// Code generated by protoc-gen-kresolver. DO NOT EDIT.

package container

import (
	measurement_unit "github.com/tmds-io/masterdata/contract/measurement_unit"
	mock "github.com/tmds-io/masterdata/contract/measurement_unit/mock"
	container "gitlab.com/tmds-io/core-model/hyperion/kore.git/v2/core/container"
)

func init() {
	// Registering MeasurementUnitHandler service
	container.Register(measurement_unit.NewMeasurementUnitHandlerServiceWithDefaultClient).
		Alias(measurement_unit.MeasurementUnitHandlerRegistryServiceName).
		Mock(mock.NewMockMeasurementUnitHandlerService).
		Tag("service.client").
		Lazy(true)
}
