// Code generated by protoc-gen-kresolver. DO NOT EDIT.

package container

import (
	category "github.com/tmds-io/masterdata/contract/category"
	mock "github.com/tmds-io/masterdata/contract/category/mock"
	container "gitlab.com/tmds-io/core-model/hyperion/kore.git/v2/core/container"
)

func init() {
	// Registering CategoryHandler service
	container.Register(category.NewCategoryHandlerServiceWithDefaultClient).
		Alias(category.CategoryHandlerRegistryServiceName).
		Mock(mock.NewMockCategoryHandlerService).
		Tag("service.client").
		Lazy(true)
}
