# syntax=docker/dockerfile:1
FROM go-base-dev AS builder-dev
WORKDIR /workdir

COPY . .

RUN --mount=type=ssh --mount=type=cache,target=/go/pkg go mod download
RUN --mount=type=cache,target=/root/.cache/go-build --mount=type=cache,target=/go/pkg go generate ./...
RUN --mount=type=cache,target=/root/.cache/go-build --mount=type=cache,target=/go/pkg go build -o server .

###### PROD: DON'T TOUCH IT ! #######################
FROM alpine AS builder-prod
RUN apk --no-cache add tzdata ca-certificates
ADD server /server
ADD config/kore.yaml /kore.yaml
ADD config/kore_dev.yaml /kore_dev.yaml
ENTRYPOINT [ "/server" ]