// Code generated by container-gen. DO NOT EDIT.

package main

import (
	import_0 "github.com/tmds-io/masterdata/service/model/settings"
	_ "gitlab.com/tmds-io/core-model/hyperion/contract.git/v2/services"
	"gitlab.com/tmds-io/core-model/hyperion/kore.git/v2/core/container"
)

func init() {
	container.Register(import_0.NewSettingsRepository)
}
