// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.21.12
// source: contract/measurement_unit/measurement_unit.proto

package measurement_unit

import (
	db "gitlab.com/tmds-io/core-model/hyperion/kore.git/v2/core/db"
	arangodb "gitlab.com/tmds-io/core-model/hyperion/kore.git/v2/core/db/arangodb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MeasurementUnit struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                  string        `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                                                  // Unique identifier for the MeasurementUnit
	Key                 string        `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`                                                                // Unique Key code
	Name                string        `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`                                                              // Name of the measurement unit
	Type                string        `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`                                                              // Type of the measurement unit (e.g. length, weight, ...)
	BaseFactorReal      float32       `protobuf:"fixed32,5,opt,name=base_factor_real,json=baseFactorReal,proto3" json:"base_factor_real,omitempty"`                // Real part of the Base factor
	BaseFactorImaginary float32       `protobuf:"fixed32,6,opt,name=base_factor_imaginary,json=baseFactorImaginary,proto3" json:"base_factor_imaginary,omitempty"` // Imaginary part of the Base factor
	UpdatedAt           *db.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`                                   // Date of the last update
}

func (x *MeasurementUnit) Reset() {
	*x = MeasurementUnit{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contract_measurement_unit_measurement_unit_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MeasurementUnit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeasurementUnit) ProtoMessage() {}

func (x *MeasurementUnit) ProtoReflect() protoreflect.Message {
	mi := &file_contract_measurement_unit_measurement_unit_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeasurementUnit.ProtoReflect.Descriptor instead.
func (*MeasurementUnit) Descriptor() ([]byte, []int) {
	return file_contract_measurement_unit_measurement_unit_proto_rawDescGZIP(), []int{0}
}

func (x *MeasurementUnit) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MeasurementUnit) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *MeasurementUnit) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MeasurementUnit) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *MeasurementUnit) GetBaseFactorReal() float32 {
	if x != nil {
		return x.BaseFactorReal
	}
	return 0
}

func (x *MeasurementUnit) GetBaseFactorImaginary() float32 {
	if x != nil {
		return x.BaseFactorImaginary
	}
	return 0
}

func (x *MeasurementUnit) GetUpdatedAt() *db.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateMeasurementUnitRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MeasurementUnit *MeasurementUnit `protobuf:"bytes,1,opt,name=measurement_unit,json=measurementUnit,proto3" json:"measurement_unit,omitempty"`
}

func (x *CreateMeasurementUnitRequest) Reset() {
	*x = CreateMeasurementUnitRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contract_measurement_unit_measurement_unit_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateMeasurementUnitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMeasurementUnitRequest) ProtoMessage() {}

func (x *CreateMeasurementUnitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contract_measurement_unit_measurement_unit_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMeasurementUnitRequest.ProtoReflect.Descriptor instead.
func (*CreateMeasurementUnitRequest) Descriptor() ([]byte, []int) {
	return file_contract_measurement_unit_measurement_unit_proto_rawDescGZIP(), []int{1}
}

func (x *CreateMeasurementUnitRequest) GetMeasurementUnit() *MeasurementUnit {
	if x != nil {
		return x.MeasurementUnit
	}
	return nil
}

type CreateMeasurementUnitResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CreateMeasurementUnitResponse) Reset() {
	*x = CreateMeasurementUnitResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contract_measurement_unit_measurement_unit_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateMeasurementUnitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMeasurementUnitResponse) ProtoMessage() {}

func (x *CreateMeasurementUnitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contract_measurement_unit_measurement_unit_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMeasurementUnitResponse.ProtoReflect.Descriptor instead.
func (*CreateMeasurementUnitResponse) Descriptor() ([]byte, []int) {
	return file_contract_measurement_unit_measurement_unit_proto_rawDescGZIP(), []int{2}
}

func (x *CreateMeasurementUnitResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ReadMeasurementUnitRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ReadMeasurementUnitRequest) Reset() {
	*x = ReadMeasurementUnitRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contract_measurement_unit_measurement_unit_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadMeasurementUnitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadMeasurementUnitRequest) ProtoMessage() {}

func (x *ReadMeasurementUnitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contract_measurement_unit_measurement_unit_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadMeasurementUnitRequest.ProtoReflect.Descriptor instead.
func (*ReadMeasurementUnitRequest) Descriptor() ([]byte, []int) {
	return file_contract_measurement_unit_measurement_unit_proto_rawDescGZIP(), []int{3}
}

func (x *ReadMeasurementUnitRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ReadMeasurementUnitResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MeasurementUnit *MeasurementUnit `protobuf:"bytes,1,opt,name=measurement_unit,json=measurementUnit,proto3" json:"measurement_unit,omitempty"`
}

func (x *ReadMeasurementUnitResponse) Reset() {
	*x = ReadMeasurementUnitResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contract_measurement_unit_measurement_unit_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadMeasurementUnitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadMeasurementUnitResponse) ProtoMessage() {}

func (x *ReadMeasurementUnitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contract_measurement_unit_measurement_unit_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadMeasurementUnitResponse.ProtoReflect.Descriptor instead.
func (*ReadMeasurementUnitResponse) Descriptor() ([]byte, []int) {
	return file_contract_measurement_unit_measurement_unit_proto_rawDescGZIP(), []int{4}
}

func (x *ReadMeasurementUnitResponse) GetMeasurementUnit() *MeasurementUnit {
	if x != nil {
		return x.MeasurementUnit
	}
	return nil
}

type UpdateMeasurementUnitRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MeasurementUnit *MeasurementUnit `protobuf:"bytes,1,opt,name=measurement_unit,json=measurementUnit,proto3" json:"measurement_unit,omitempty"`
}

func (x *UpdateMeasurementUnitRequest) Reset() {
	*x = UpdateMeasurementUnitRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contract_measurement_unit_measurement_unit_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateMeasurementUnitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMeasurementUnitRequest) ProtoMessage() {}

func (x *UpdateMeasurementUnitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contract_measurement_unit_measurement_unit_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMeasurementUnitRequest.ProtoReflect.Descriptor instead.
func (*UpdateMeasurementUnitRequest) Descriptor() ([]byte, []int) {
	return file_contract_measurement_unit_measurement_unit_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateMeasurementUnitRequest) GetMeasurementUnit() *MeasurementUnit {
	if x != nil {
		return x.MeasurementUnit
	}
	return nil
}

type UpdateMeasurementUnitResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MeasurementUnit *MeasurementUnit `protobuf:"bytes,1,opt,name=measurement_unit,json=measurementUnit,proto3" json:"measurement_unit,omitempty"`
}

func (x *UpdateMeasurementUnitResponse) Reset() {
	*x = UpdateMeasurementUnitResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contract_measurement_unit_measurement_unit_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateMeasurementUnitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMeasurementUnitResponse) ProtoMessage() {}

func (x *UpdateMeasurementUnitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contract_measurement_unit_measurement_unit_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMeasurementUnitResponse.ProtoReflect.Descriptor instead.
func (*UpdateMeasurementUnitResponse) Descriptor() ([]byte, []int) {
	return file_contract_measurement_unit_measurement_unit_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateMeasurementUnitResponse) GetMeasurementUnit() *MeasurementUnit {
	if x != nil {
		return x.MeasurementUnit
	}
	return nil
}

type DeleteMeasurementUnitRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteMeasurementUnitRequest) Reset() {
	*x = DeleteMeasurementUnitRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contract_measurement_unit_measurement_unit_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteMeasurementUnitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMeasurementUnitRequest) ProtoMessage() {}

func (x *DeleteMeasurementUnitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contract_measurement_unit_measurement_unit_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMeasurementUnitRequest.ProtoReflect.Descriptor instead.
func (*DeleteMeasurementUnitRequest) Descriptor() ([]byte, []int) {
	return file_contract_measurement_unit_measurement_unit_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteMeasurementUnitRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteMeasurementUnitResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteMeasurementUnitResponse) Reset() {
	*x = DeleteMeasurementUnitResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contract_measurement_unit_measurement_unit_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteMeasurementUnitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMeasurementUnitResponse) ProtoMessage() {}

func (x *DeleteMeasurementUnitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contract_measurement_unit_measurement_unit_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMeasurementUnitResponse.ProtoReflect.Descriptor instead.
func (*DeleteMeasurementUnitResponse) Descriptor() ([]byte, []int) {
	return file_contract_measurement_unit_measurement_unit_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteMeasurementUnitResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type SearchMeasurementUnitsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Filters *arangodb.Filters `protobuf:"bytes,1,opt,name=filters,proto3" json:"filters,omitempty"`
}

func (x *SearchMeasurementUnitsRequest) Reset() {
	*x = SearchMeasurementUnitsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contract_measurement_unit_measurement_unit_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchMeasurementUnitsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchMeasurementUnitsRequest) ProtoMessage() {}

func (x *SearchMeasurementUnitsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contract_measurement_unit_measurement_unit_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchMeasurementUnitsRequest.ProtoReflect.Descriptor instead.
func (*SearchMeasurementUnitsRequest) Descriptor() ([]byte, []int) {
	return file_contract_measurement_unit_measurement_unit_proto_rawDescGZIP(), []int{9}
}

func (x *SearchMeasurementUnitsRequest) GetFilters() *arangodb.Filters {
	if x != nil {
		return x.Filters
	}
	return nil
}

type SearchMeasurementUnitsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MeasurementUnits []*MeasurementUnit       `protobuf:"bytes,1,rep,name=measurement_units,json=measurementUnits,proto3" json:"measurement_units,omitempty"`
	Pagination       *arangodb.PaginationData `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (x *SearchMeasurementUnitsResponse) Reset() {
	*x = SearchMeasurementUnitsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contract_measurement_unit_measurement_unit_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchMeasurementUnitsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchMeasurementUnitsResponse) ProtoMessage() {}

func (x *SearchMeasurementUnitsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contract_measurement_unit_measurement_unit_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchMeasurementUnitsResponse.ProtoReflect.Descriptor instead.
func (*SearchMeasurementUnitsResponse) Descriptor() ([]byte, []int) {
	return file_contract_measurement_unit_measurement_unit_proto_rawDescGZIP(), []int{10}
}

func (x *SearchMeasurementUnitsResponse) GetMeasurementUnits() []*MeasurementUnit {
	if x != nil {
		return x.MeasurementUnits
	}
	return nil
}

func (x *SearchMeasurementUnitsResponse) GetPagination() *arangodb.PaginationData {
	if x != nil {
		return x.Pagination
	}
	return nil
}

var File_contract_measurement_unit_measurement_unit_proto protoreflect.FileDescriptor

var file_contract_measurement_unit_measurement_unit_proto_rawDesc = []byte{
	0x0a, 0x30, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2f, 0x6d, 0x65, 0x61, 0x73, 0x75,
	0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x75, 0x6e, 0x69, 0x74, 0x2f, 0x6d, 0x65, 0x61, 0x73,
	0x75, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x75, 0x6e, 0x69, 0x74, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x08, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x1a, 0x17, 0x63, 0x6f,
	0x72, 0x65, 0x2f, 0x64, 0x62, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1d, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x64, 0x62, 0x2f, 0x61,
	0x72, 0x61, 0x6e, 0x67, 0x6f, 0x64, 0x62, 0x2f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0xe7, 0x01, 0x0a, 0x0f, 0x4d, 0x65, 0x61, 0x73, 0x75, 0x72, 0x65,
	0x6d, 0x65, 0x6e, 0x74, 0x55, 0x6e, 0x69, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x12, 0x28, 0x0a, 0x10, 0x62, 0x61, 0x73, 0x65, 0x5f, 0x66, 0x61, 0x63, 0x74, 0x6f,
	0x72, 0x5f, 0x72, 0x65, 0x61, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0e, 0x62, 0x61,
	0x73, 0x65, 0x46, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x61, 0x6c, 0x12, 0x32, 0x0a, 0x15,
	0x62, 0x61, 0x73, 0x65, 0x5f, 0x66, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x5f, 0x69, 0x6d, 0x61, 0x67,
	0x69, 0x6e, 0x61, 0x72, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x02, 0x52, 0x13, 0x62, 0x61, 0x73,
	0x65, 0x46, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x49, 0x6d, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x72, 0x79,
	0x12, 0x2c, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x64, 0x62, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x64,
	0x0a, 0x1c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x61, 0x73, 0x75, 0x72, 0x65, 0x6d,
	0x65, 0x6e, 0x74, 0x55, 0x6e, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x44,
	0x0a, 0x10, 0x6d, 0x65, 0x61, 0x73, 0x75, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x75, 0x6e,
	0x69, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72,
	0x61, 0x63, 0x74, 0x2e, 0x4d, 0x65, 0x61, 0x73, 0x75, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x55,
	0x6e, 0x69, 0x74, 0x52, 0x0f, 0x6d, 0x65, 0x61, 0x73, 0x75, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74,
	0x55, 0x6e, 0x69, 0x74, 0x22, 0x2f, 0x0a, 0x1d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x65,
	0x61, 0x73, 0x75, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x55, 0x6e, 0x69, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x2c, 0x0a, 0x1a, 0x52, 0x65, 0x61, 0x64, 0x4d, 0x65, 0x61,
	0x73, 0x75, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x55, 0x6e, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x22, 0x63, 0x0a, 0x1b, 0x52, 0x65, 0x61, 0x64, 0x4d, 0x65, 0x61, 0x73, 0x75,
	0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x55, 0x6e, 0x69, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x44, 0x0a, 0x10, 0x6d, 0x65, 0x61, 0x73, 0x75, 0x72, 0x65, 0x6d, 0x65, 0x6e,
	0x74, 0x5f, 0x75, 0x6e, 0x69, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x63,
	0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2e, 0x4d, 0x65, 0x61, 0x73, 0x75, 0x72, 0x65, 0x6d,
	0x65, 0x6e, 0x74, 0x55, 0x6e, 0x69, 0x74, 0x52, 0x0f, 0x6d, 0x65, 0x61, 0x73, 0x75, 0x72, 0x65,
	0x6d, 0x65, 0x6e, 0x74, 0x55, 0x6e, 0x69, 0x74, 0x22, 0x64, 0x0a, 0x1c, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x4d, 0x65, 0x61, 0x73, 0x75, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x55, 0x6e, 0x69,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x44, 0x0a, 0x10, 0x6d, 0x65, 0x61, 0x73,
	0x75, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x75, 0x6e, 0x69, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x19, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2e, 0x4d, 0x65,
	0x61, 0x73, 0x75, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x55, 0x6e, 0x69, 0x74, 0x52, 0x0f, 0x6d,
	0x65, 0x61, 0x73, 0x75, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x55, 0x6e, 0x69, 0x74, 0x22, 0x65,
	0x0a, 0x1d, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x61, 0x73, 0x75, 0x72, 0x65, 0x6d,
	0x65, 0x6e, 0x74, 0x55, 0x6e, 0x69, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x44, 0x0a, 0x10, 0x6d, 0x65, 0x61, 0x73, 0x75, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x75,
	0x6e, 0x69, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x63, 0x6f, 0x6e, 0x74,
	0x72, 0x61, 0x63, 0x74, 0x2e, 0x4d, 0x65, 0x61, 0x73, 0x75, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74,
	0x55, 0x6e, 0x69, 0x74, 0x52, 0x0f, 0x6d, 0x65, 0x61, 0x73, 0x75, 0x72, 0x65, 0x6d, 0x65, 0x6e,
	0x74, 0x55, 0x6e, 0x69, 0x74, 0x22, 0x2e, 0x0a, 0x1c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d,
	0x65, 0x61, 0x73, 0x75, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x55, 0x6e, 0x69, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x2f, 0x0a, 0x1d, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d,
	0x65, 0x61, 0x73, 0x75, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x55, 0x6e, 0x69, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x4c, 0x0a, 0x1d, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68,
	0x4d, 0x65, 0x61, 0x73, 0x75, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x55, 0x6e, 0x69, 0x74, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2b, 0x0a, 0x07, 0x66, 0x69, 0x6c, 0x74, 0x65,
	0x72, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x61, 0x72, 0x61, 0x6e, 0x67,
	0x6f, 0x64, 0x62, 0x2e, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x52, 0x07, 0x66, 0x69, 0x6c,
	0x74, 0x65, 0x72, 0x73, 0x22, 0xa2, 0x01, 0x0a, 0x1e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x4d,
	0x65, 0x61, 0x73, 0x75, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x55, 0x6e, 0x69, 0x74, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x46, 0x0a, 0x11, 0x6d, 0x65, 0x61, 0x73, 0x75,
	0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x75, 0x6e, 0x69, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x19, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2e, 0x4d, 0x65,
	0x61, 0x73, 0x75, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x55, 0x6e, 0x69, 0x74, 0x52, 0x10, 0x6d,
	0x65, 0x61, 0x73, 0x75, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x55, 0x6e, 0x69, 0x74, 0x73, 0x12,
	0x38, 0x0a, 0x0a, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x61, 0x72, 0x61, 0x6e, 0x67, 0x6f, 0x64, 0x62, 0x2e, 0x50,
	0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x0a, 0x70,
	0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x32, 0xa7, 0x04, 0x0a, 0x16, 0x4d, 0x65,
	0x61, 0x73, 0x75, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x55, 0x6e, 0x69, 0x74, 0x48, 0x61, 0x6e,
	0x64, 0x6c, 0x65, 0x72, 0x12, 0x68, 0x0a, 0x15, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x65,
	0x61, 0x73, 0x75, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x55, 0x6e, 0x69, 0x74, 0x12, 0x26, 0x2e,
	0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d,
	0x65, 0x61, 0x73, 0x75, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x55, 0x6e, 0x69, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74,
	0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x61, 0x73, 0x75, 0x72, 0x65, 0x6d, 0x65,
	0x6e, 0x74, 0x55, 0x6e, 0x69, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x62,
	0x0a, 0x13, 0x52, 0x65, 0x61, 0x64, 0x4d, 0x65, 0x61, 0x73, 0x75, 0x72, 0x65, 0x6d, 0x65, 0x6e,
	0x74, 0x55, 0x6e, 0x69, 0x74, 0x12, 0x24, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74,
	0x2e, 0x52, 0x65, 0x61, 0x64, 0x4d, 0x65, 0x61, 0x73, 0x75, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74,
	0x55, 0x6e, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x63, 0x6f,
	0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x4d, 0x65, 0x61, 0x73, 0x75,
	0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x55, 0x6e, 0x69, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x68, 0x0a, 0x15, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x61, 0x73,
	0x75, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x55, 0x6e, 0x69, 0x74, 0x12, 0x26, 0x2e, 0x63, 0x6f,
	0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x61,
	0x73, 0x75, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x55, 0x6e, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2e, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x61, 0x73, 0x75, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74,
	0x55, 0x6e, 0x69, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x68, 0x0a, 0x15,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x65, 0x61, 0x73, 0x75, 0x72, 0x65, 0x6d, 0x65, 0x6e,
	0x74, 0x55, 0x6e, 0x69, 0x74, 0x12, 0x26, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74,
	0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x65, 0x61, 0x73, 0x75, 0x72, 0x65, 0x6d, 0x65,
	0x6e, 0x74, 0x55, 0x6e, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e,
	0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d,
	0x65, 0x61, 0x73, 0x75, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x55, 0x6e, 0x69, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x6b, 0x0a, 0x16, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68,
	0x4d, 0x65, 0x61, 0x73, 0x75, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x55, 0x6e, 0x69, 0x74, 0x73,
	0x12, 0x27, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2e, 0x53, 0x65, 0x61, 0x72,
	0x63, 0x68, 0x4d, 0x65, 0x61, 0x73, 0x75, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x55, 0x6e, 0x69,
	0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x28, 0x2e, 0x63, 0x6f, 0x6e, 0x74,
	0x72, 0x61, 0x63, 0x74, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x4d, 0x65, 0x61, 0x73, 0x75,
	0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x55, 0x6e, 0x69, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x42, 0x4a, 0x5a, 0x48, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x74, 0x6d, 0x64, 0x73, 0x2d, 0x69, 0x6f, 0x2f, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72,
	0x64, 0x61, 0x74, 0x61, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2f, 0x6d, 0x65,
	0x61, 0x73, 0x75, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x75, 0x6e, 0x69, 0x74, 0x3b, 0x6d,
	0x65, 0x61, 0x73, 0x75, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x75, 0x6e, 0x69, 0x74, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_contract_measurement_unit_measurement_unit_proto_rawDescOnce sync.Once
	file_contract_measurement_unit_measurement_unit_proto_rawDescData = file_contract_measurement_unit_measurement_unit_proto_rawDesc
)

func file_contract_measurement_unit_measurement_unit_proto_rawDescGZIP() []byte {
	file_contract_measurement_unit_measurement_unit_proto_rawDescOnce.Do(func() {
		file_contract_measurement_unit_measurement_unit_proto_rawDescData = protoimpl.X.CompressGZIP(file_contract_measurement_unit_measurement_unit_proto_rawDescData)
	})
	return file_contract_measurement_unit_measurement_unit_proto_rawDescData
}

var file_contract_measurement_unit_measurement_unit_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_contract_measurement_unit_measurement_unit_proto_goTypes = []interface{}{
	(*MeasurementUnit)(nil),                // 0: contract.MeasurementUnit
	(*CreateMeasurementUnitRequest)(nil),   // 1: contract.CreateMeasurementUnitRequest
	(*CreateMeasurementUnitResponse)(nil),  // 2: contract.CreateMeasurementUnitResponse
	(*ReadMeasurementUnitRequest)(nil),     // 3: contract.ReadMeasurementUnitRequest
	(*ReadMeasurementUnitResponse)(nil),    // 4: contract.ReadMeasurementUnitResponse
	(*UpdateMeasurementUnitRequest)(nil),   // 5: contract.UpdateMeasurementUnitRequest
	(*UpdateMeasurementUnitResponse)(nil),  // 6: contract.UpdateMeasurementUnitResponse
	(*DeleteMeasurementUnitRequest)(nil),   // 7: contract.DeleteMeasurementUnitRequest
	(*DeleteMeasurementUnitResponse)(nil),  // 8: contract.DeleteMeasurementUnitResponse
	(*SearchMeasurementUnitsRequest)(nil),  // 9: contract.SearchMeasurementUnitsRequest
	(*SearchMeasurementUnitsResponse)(nil), // 10: contract.SearchMeasurementUnitsResponse
	(*db.Timestamp)(nil),                   // 11: db.Timestamp
	(*arangodb.Filters)(nil),               // 12: arangodb.Filters
	(*arangodb.PaginationData)(nil),        // 13: arangodb.PaginationData
}
var file_contract_measurement_unit_measurement_unit_proto_depIdxs = []int32{
	11, // 0: contract.MeasurementUnit.updated_at:type_name -> db.Timestamp
	0,  // 1: contract.CreateMeasurementUnitRequest.measurement_unit:type_name -> contract.MeasurementUnit
	0,  // 2: contract.ReadMeasurementUnitResponse.measurement_unit:type_name -> contract.MeasurementUnit
	0,  // 3: contract.UpdateMeasurementUnitRequest.measurement_unit:type_name -> contract.MeasurementUnit
	0,  // 4: contract.UpdateMeasurementUnitResponse.measurement_unit:type_name -> contract.MeasurementUnit
	12, // 5: contract.SearchMeasurementUnitsRequest.filters:type_name -> arangodb.Filters
	0,  // 6: contract.SearchMeasurementUnitsResponse.measurement_units:type_name -> contract.MeasurementUnit
	13, // 7: contract.SearchMeasurementUnitsResponse.pagination:type_name -> arangodb.PaginationData
	1,  // 8: contract.MeasurementUnitHandler.CreateMeasurementUnit:input_type -> contract.CreateMeasurementUnitRequest
	3,  // 9: contract.MeasurementUnitHandler.ReadMeasurementUnit:input_type -> contract.ReadMeasurementUnitRequest
	5,  // 10: contract.MeasurementUnitHandler.UpdateMeasurementUnit:input_type -> contract.UpdateMeasurementUnitRequest
	7,  // 11: contract.MeasurementUnitHandler.DeleteMeasurementUnit:input_type -> contract.DeleteMeasurementUnitRequest
	9,  // 12: contract.MeasurementUnitHandler.SearchMeasurementUnits:input_type -> contract.SearchMeasurementUnitsRequest
	2,  // 13: contract.MeasurementUnitHandler.CreateMeasurementUnit:output_type -> contract.CreateMeasurementUnitResponse
	4,  // 14: contract.MeasurementUnitHandler.ReadMeasurementUnit:output_type -> contract.ReadMeasurementUnitResponse
	6,  // 15: contract.MeasurementUnitHandler.UpdateMeasurementUnit:output_type -> contract.UpdateMeasurementUnitResponse
	8,  // 16: contract.MeasurementUnitHandler.DeleteMeasurementUnit:output_type -> contract.DeleteMeasurementUnitResponse
	10, // 17: contract.MeasurementUnitHandler.SearchMeasurementUnits:output_type -> contract.SearchMeasurementUnitsResponse
	13, // [13:18] is the sub-list for method output_type
	8,  // [8:13] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_contract_measurement_unit_measurement_unit_proto_init() }
func file_contract_measurement_unit_measurement_unit_proto_init() {
	if File_contract_measurement_unit_measurement_unit_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_contract_measurement_unit_measurement_unit_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MeasurementUnit); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_contract_measurement_unit_measurement_unit_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateMeasurementUnitRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_contract_measurement_unit_measurement_unit_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateMeasurementUnitResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_contract_measurement_unit_measurement_unit_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadMeasurementUnitRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_contract_measurement_unit_measurement_unit_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadMeasurementUnitResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_contract_measurement_unit_measurement_unit_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateMeasurementUnitRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_contract_measurement_unit_measurement_unit_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateMeasurementUnitResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_contract_measurement_unit_measurement_unit_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteMeasurementUnitRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_contract_measurement_unit_measurement_unit_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteMeasurementUnitResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_contract_measurement_unit_measurement_unit_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchMeasurementUnitsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_contract_measurement_unit_measurement_unit_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchMeasurementUnitsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_contract_measurement_unit_measurement_unit_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_contract_measurement_unit_measurement_unit_proto_goTypes,
		DependencyIndexes: file_contract_measurement_unit_measurement_unit_proto_depIdxs,
		MessageInfos:      file_contract_measurement_unit_measurement_unit_proto_msgTypes,
	}.Build()
	File_contract_measurement_unit_measurement_unit_proto = out.File
	file_contract_measurement_unit_measurement_unit_proto_rawDesc = nil
	file_contract_measurement_unit_measurement_unit_proto_goTypes = nil
	file_contract_measurement_unit_measurement_unit_proto_depIdxs = nil
}
