// Code generated by protoc-gen-kresolver. DO NOT EDIT.

//go:generate mockgen -destination=./mock/mock.go -contractPackage=github.com/tmds-io/masterdata/contract. MeasurementUnitHandlerService

package measurement_unit
