// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.21.12
// source: contract/data_definition/data_definition.proto

package data_definition

import (
	db "gitlab.com/tmds-io/core-model/hyperion/kore.git/v2/core/db"
	arangodb "gitlab.com/tmds-io/core-model/hyperion/kore.git/v2/core/db/arangodb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DataType int32

const (
	DataType_RAW       DataType = 0
	DataType_PROCESSED DataType = 1
)

// Enum value maps for DataType.
var (
	DataType_name = map[int32]string{
		0: "RAW",
		1: "PROCESSED",
	}
	DataType_value = map[string]int32{
		"RAW":       0,
		"PROCESSED": 1,
	}
)

func (x DataType) Enum() *DataType {
	p := new(DataType)
	*p = x
	return p
}

func (x DataType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DataType) Descriptor() protoreflect.EnumDescriptor {
	return file_contract_data_definition_data_definition_proto_enumTypes[0].Descriptor()
}

func (DataType) Type() protoreflect.EnumType {
	return &file_contract_data_definition_data_definition_proto_enumTypes[0]
}

func (x DataType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DataType.Descriptor instead.
func (DataType) EnumDescriptor() ([]byte, []int) {
	return file_contract_data_definition_data_definition_proto_rawDescGZIP(), []int{0}
}

type DataDefinition struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                       string        `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                                                                 // Unique identifier for the DataDefinition
	Key                      string        `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`                                                                               // Unique Key code (used as id in db)
	Name                     string        `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`                                                                             // Name of the data definition
	CategoryValueIds         []string      `protobuf:"bytes,4,rep,name=category_value_ids,json=categoryValueIds,proto3" json:"category_value_ids,omitempty"`                           // Category of the data definition
	DefaultType              DataType      `protobuf:"varint,5,opt,name=default_type,json=defaultType,proto3,enum=contract.DataType" json:"default_type,omitempty"`                    // Type of the data definition by default
	DefaultSegmentIds        []string      `protobuf:"bytes,6,rep,name=default_segment_ids,json=defaultSegmentIds,proto3" json:"default_segment_ids,omitempty"`                        // Association SegmentId / Value
	DefaultMeasurementUnitId string        `protobuf:"bytes,7,opt,name=default_measurement_unit_id,json=defaultMeasurementUnitId,proto3" json:"default_measurement_unit_id,omitempty"` // Unit of the data definition by default
	Visibility               string        `protobuf:"bytes,8,opt,name=visibility,proto3" json:"visibility,omitempty"`                                                                 // Should the data definition be visible
	IsDefaultOverloadable    bool          `protobuf:"varint,9,opt,name=is_default_overloadable,json=isDefaultOverloadable,proto3" json:"is_default_overloadable,omitempty"`
	Description              string        `protobuf:"bytes,10,opt,name=description,proto3" json:"description,omitempty"`
	UpdatedAt                *db.Timestamp `protobuf:"bytes,101,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"` // Date of the last update
}

func (x *DataDefinition) Reset() {
	*x = DataDefinition{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contract_data_definition_data_definition_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataDefinition) ProtoMessage() {}

func (x *DataDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_contract_data_definition_data_definition_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataDefinition.ProtoReflect.Descriptor instead.
func (*DataDefinition) Descriptor() ([]byte, []int) {
	return file_contract_data_definition_data_definition_proto_rawDescGZIP(), []int{0}
}

func (x *DataDefinition) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DataDefinition) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *DataDefinition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DataDefinition) GetCategoryValueIds() []string {
	if x != nil {
		return x.CategoryValueIds
	}
	return nil
}

func (x *DataDefinition) GetDefaultType() DataType {
	if x != nil {
		return x.DefaultType
	}
	return DataType_RAW
}

func (x *DataDefinition) GetDefaultSegmentIds() []string {
	if x != nil {
		return x.DefaultSegmentIds
	}
	return nil
}

func (x *DataDefinition) GetDefaultMeasurementUnitId() string {
	if x != nil {
		return x.DefaultMeasurementUnitId
	}
	return ""
}

func (x *DataDefinition) GetVisibility() string {
	if x != nil {
		return x.Visibility
	}
	return ""
}

func (x *DataDefinition) GetIsDefaultOverloadable() bool {
	if x != nil {
		return x.IsDefaultOverloadable
	}
	return false
}

func (x *DataDefinition) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *DataDefinition) GetUpdatedAt() *db.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Request to read a DataDefinition by ID.
type ReadDataDefinitionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // ID of the DataDefinition to read
}

func (x *ReadDataDefinitionRequest) Reset() {
	*x = ReadDataDefinitionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contract_data_definition_data_definition_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadDataDefinitionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadDataDefinitionRequest) ProtoMessage() {}

func (x *ReadDataDefinitionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contract_data_definition_data_definition_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadDataDefinitionRequest.ProtoReflect.Descriptor instead.
func (*ReadDataDefinitionRequest) Descriptor() ([]byte, []int) {
	return file_contract_data_definition_data_definition_proto_rawDescGZIP(), []int{1}
}

func (x *ReadDataDefinitionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Response containing a DataDefinition.
type ReadDataDefinitionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DataDefinition *DataDefinition `protobuf:"bytes,1,opt,name=data_definition,json=dataDefinition,proto3" json:"data_definition,omitempty"` // The retrieved DataDefinition
}

func (x *ReadDataDefinitionResponse) Reset() {
	*x = ReadDataDefinitionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contract_data_definition_data_definition_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadDataDefinitionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadDataDefinitionResponse) ProtoMessage() {}

func (x *ReadDataDefinitionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contract_data_definition_data_definition_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadDataDefinitionResponse.ProtoReflect.Descriptor instead.
func (*ReadDataDefinitionResponse) Descriptor() ([]byte, []int) {
	return file_contract_data_definition_data_definition_proto_rawDescGZIP(), []int{2}
}

func (x *ReadDataDefinitionResponse) GetDataDefinition() *DataDefinition {
	if x != nil {
		return x.DataDefinition
	}
	return nil
}

// Request to save a DataDefinition.
type CreateDataDefinitionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DataDefinition *DataDefinition `protobuf:"bytes,1,opt,name=data_definition,json=dataDefinition,proto3" json:"data_definition,omitempty"` // The DataDefinition to save
}

func (x *CreateDataDefinitionRequest) Reset() {
	*x = CreateDataDefinitionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contract_data_definition_data_definition_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateDataDefinitionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDataDefinitionRequest) ProtoMessage() {}

func (x *CreateDataDefinitionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contract_data_definition_data_definition_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDataDefinitionRequest.ProtoReflect.Descriptor instead.
func (*CreateDataDefinitionRequest) Descriptor() ([]byte, []int) {
	return file_contract_data_definition_data_definition_proto_rawDescGZIP(), []int{3}
}

func (x *CreateDataDefinitionRequest) GetDataDefinition() *DataDefinition {
	if x != nil {
		return x.DataDefinition
	}
	return nil
}

// Response indicating the status of the save operation.
type CreateDataDefinitionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // ID of the DataDefinition created
}

func (x *CreateDataDefinitionResponse) Reset() {
	*x = CreateDataDefinitionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contract_data_definition_data_definition_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateDataDefinitionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDataDefinitionResponse) ProtoMessage() {}

func (x *CreateDataDefinitionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contract_data_definition_data_definition_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDataDefinitionResponse.ProtoReflect.Descriptor instead.
func (*CreateDataDefinitionResponse) Descriptor() ([]byte, []int) {
	return file_contract_data_definition_data_definition_proto_rawDescGZIP(), []int{4}
}

func (x *CreateDataDefinitionResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Request to save a DataDefinition.
type UpdateDataDefinitionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DataDefinition *DataDefinition `protobuf:"bytes,1,opt,name=data_definition,json=dataDefinition,proto3" json:"data_definition,omitempty"` // The DataDefinition to save
}

func (x *UpdateDataDefinitionRequest) Reset() {
	*x = UpdateDataDefinitionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contract_data_definition_data_definition_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateDataDefinitionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDataDefinitionRequest) ProtoMessage() {}

func (x *UpdateDataDefinitionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contract_data_definition_data_definition_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDataDefinitionRequest.ProtoReflect.Descriptor instead.
func (*UpdateDataDefinitionRequest) Descriptor() ([]byte, []int) {
	return file_contract_data_definition_data_definition_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateDataDefinitionRequest) GetDataDefinition() *DataDefinition {
	if x != nil {
		return x.DataDefinition
	}
	return nil
}

// Response indicating the status of the save operation.
type UpdateDataDefinitionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // ID of the DataDefinition Updated
}

func (x *UpdateDataDefinitionResponse) Reset() {
	*x = UpdateDataDefinitionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contract_data_definition_data_definition_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateDataDefinitionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDataDefinitionResponse) ProtoMessage() {}

func (x *UpdateDataDefinitionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contract_data_definition_data_definition_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDataDefinitionResponse.ProtoReflect.Descriptor instead.
func (*UpdateDataDefinitionResponse) Descriptor() ([]byte, []int) {
	return file_contract_data_definition_data_definition_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateDataDefinitionResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Request to delete a DataDefinition by ID.
type DeleteDataDefinitionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // ID of the DataDefinition to delete
}

func (x *DeleteDataDefinitionRequest) Reset() {
	*x = DeleteDataDefinitionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contract_data_definition_data_definition_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteDataDefinitionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDataDefinitionRequest) ProtoMessage() {}

func (x *DeleteDataDefinitionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contract_data_definition_data_definition_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDataDefinitionRequest.ProtoReflect.Descriptor instead.
func (*DeleteDataDefinitionRequest) Descriptor() ([]byte, []int) {
	return file_contract_data_definition_data_definition_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteDataDefinitionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Response indicating the status of the delete operation.
type DeleteDataDefinitionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // ID of the DataDefinition deleted
}

func (x *DeleteDataDefinitionResponse) Reset() {
	*x = DeleteDataDefinitionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contract_data_definition_data_definition_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteDataDefinitionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDataDefinitionResponse) ProtoMessage() {}

func (x *DeleteDataDefinitionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contract_data_definition_data_definition_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDataDefinitionResponse.ProtoReflect.Descriptor instead.
func (*DeleteDataDefinitionResponse) Descriptor() ([]byte, []int) {
	return file_contract_data_definition_data_definition_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteDataDefinitionResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Request to search for DataDefinitions based on criteria.
type SearchDataDefinitionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Filters *arangodb.Filters `protobuf:"bytes,1,opt,name=filters,proto3" json:"filters,omitempty"`
}

func (x *SearchDataDefinitionRequest) Reset() {
	*x = SearchDataDefinitionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contract_data_definition_data_definition_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchDataDefinitionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchDataDefinitionRequest) ProtoMessage() {}

func (x *SearchDataDefinitionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contract_data_definition_data_definition_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchDataDefinitionRequest.ProtoReflect.Descriptor instead.
func (*SearchDataDefinitionRequest) Descriptor() ([]byte, []int) {
	return file_contract_data_definition_data_definition_proto_rawDescGZIP(), []int{9}
}

func (x *SearchDataDefinitionRequest) GetFilters() *arangodb.Filters {
	if x != nil {
		return x.Filters
	}
	return nil
}

// Response containing a list of matching DataDefinitions.
type SearchDataDefinitionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DataDefinitions []*DataDefinition        `protobuf:"bytes,1,rep,name=data_definitions,json=dataDefinitions,proto3" json:"data_definitions,omitempty"` // List of matching DataDefinitions
	Pagination      *arangodb.PaginationData `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (x *SearchDataDefinitionResponse) Reset() {
	*x = SearchDataDefinitionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contract_data_definition_data_definition_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchDataDefinitionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchDataDefinitionResponse) ProtoMessage() {}

func (x *SearchDataDefinitionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contract_data_definition_data_definition_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchDataDefinitionResponse.ProtoReflect.Descriptor instead.
func (*SearchDataDefinitionResponse) Descriptor() ([]byte, []int) {
	return file_contract_data_definition_data_definition_proto_rawDescGZIP(), []int{10}
}

func (x *SearchDataDefinitionResponse) GetDataDefinitions() []*DataDefinition {
	if x != nil {
		return x.DataDefinitions
	}
	return nil
}

func (x *SearchDataDefinitionResponse) GetPagination() *arangodb.PaginationData {
	if x != nil {
		return x.Pagination
	}
	return nil
}

var File_contract_data_definition_data_definition_proto protoreflect.FileDescriptor

var file_contract_data_definition_data_definition_proto_rawDesc = []byte{
	0x0a, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x5f,
	0x64, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x5f,
	0x64, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x1a, 0x17, 0x63, 0x6f, 0x72, 0x65,
	0x2f, 0x64, 0x62, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x1d, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x64, 0x62, 0x2f, 0x61, 0x72, 0x61,
	0x6e, 0x67, 0x6f, 0x64, 0x62, 0x2f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0xc2, 0x03, 0x0a, 0x0e, 0x44, 0x61, 0x74, 0x61, 0x44, 0x65, 0x66, 0x69, 0x6e,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x2c, 0x0a, 0x12, 0x63,
	0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x5f, 0x69, 0x64,
	0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x10, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72,
	0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x49, 0x64, 0x73, 0x12, 0x35, 0x0a, 0x0c, 0x64, 0x65, 0x66,
	0x61, 0x75, 0x6c, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x12, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x54,
	0x79, 0x70, 0x65, 0x52, 0x0b, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x2e, 0x0a, 0x13, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x5f, 0x73, 0x65, 0x67, 0x6d,
	0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x09, 0x52, 0x11, 0x64,
	0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x73,
	0x12, 0x3d, 0x0a, 0x1b, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x5f, 0x6d, 0x65, 0x61, 0x73,
	0x75, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x75, 0x6e, 0x69, 0x74, 0x5f, 0x69, 0x64, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x18, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x4d, 0x65,
	0x61, 0x73, 0x75, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x55, 0x6e, 0x69, 0x74, 0x49, 0x64, 0x12,
	0x1e, 0x0a, 0x0a, 0x76, 0x69, 0x73, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x76, 0x69, 0x73, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x12,
	0x36, 0x0a, 0x17, 0x69, 0x73, 0x5f, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x5f, 0x6f, 0x76,
	0x65, 0x72, 0x6c, 0x6f, 0x61, 0x64, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x15, 0x69, 0x73, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x4f, 0x76, 0x65, 0x72, 0x6c,
	0x6f, 0x61, 0x64, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2c, 0x0a, 0x0a, 0x75, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x65, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e,
	0x64, 0x62, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x75, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x2b, 0x0a, 0x19, 0x52, 0x65, 0x61, 0x64, 0x44,
	0x61, 0x74, 0x61, 0x44, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x22, 0x5f, 0x0a, 0x1a, 0x52, 0x65, 0x61, 0x64, 0x44, 0x61, 0x74, 0x61,
	0x44, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x41, 0x0a, 0x0f, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x64, 0x65, 0x66, 0x69, 0x6e,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x63, 0x6f,
	0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x44, 0x65, 0x66, 0x69, 0x6e,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0e, 0x64, 0x61, 0x74, 0x61, 0x44, 0x65, 0x66, 0x69, 0x6e,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x60, 0x0a, 0x1b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44,
	0x61, 0x74, 0x61, 0x44, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x41, 0x0a, 0x0f, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x64, 0x65, 0x66,
	0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e,
	0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x44, 0x65, 0x66,
	0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0e, 0x64, 0x61, 0x74, 0x61, 0x44, 0x65, 0x66,
	0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x2e, 0x0a, 0x1c, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x44, 0x61, 0x74, 0x61, 0x44, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x60, 0x0a, 0x1b, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x44, 0x61, 0x74, 0x61, 0x44, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x41, 0x0a, 0x0f, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x64,
	0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x18, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x44,
	0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0e, 0x64, 0x61, 0x74, 0x61, 0x44,
	0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x2e, 0x0a, 0x1c, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x44, 0x61, 0x74, 0x61, 0x44, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x2d, 0x0a, 0x1b, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x44, 0x61, 0x74, 0x61, 0x44, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x2e, 0x0a, 0x1c, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x44, 0x61, 0x74, 0x61, 0x44, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x4a, 0x0a, 0x1b, 0x53, 0x65, 0x61, 0x72,
	0x63, 0x68, 0x44, 0x61, 0x74, 0x61, 0x44, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2b, 0x0a, 0x07, 0x66, 0x69, 0x6c, 0x74, 0x65,
	0x72, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x61, 0x72, 0x61, 0x6e, 0x67,
	0x6f, 0x64, 0x62, 0x2e, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x52, 0x07, 0x66, 0x69, 0x6c,
	0x74, 0x65, 0x72, 0x73, 0x22, 0x9d, 0x01, 0x0a, 0x1c, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x44,
	0x61, 0x74, 0x61, 0x44, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x43, 0x0a, 0x10, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x64, 0x65,
	0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x18, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x44,
	0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0f, 0x64, 0x61, 0x74, 0x61, 0x44,
	0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x38, 0x0a, 0x0a, 0x70, 0x61,
	0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18,
	0x2e, 0x61, 0x72, 0x61, 0x6e, 0x67, 0x6f, 0x64, 0x62, 0x2e, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x0a, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x2a, 0x22, 0x0a, 0x08, 0x44, 0x61, 0x74, 0x61, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x07, 0x0a, 0x03, 0x52, 0x41, 0x57, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x50, 0x52, 0x4f,
	0x43, 0x45, 0x53, 0x53, 0x45, 0x44, 0x10, 0x01, 0x32, 0xd8, 0x03, 0x0a, 0x15, 0x44, 0x61, 0x74,
	0x61, 0x44, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x61, 0x6e, 0x64, 0x6c,
	0x65, 0x72, 0x12, 0x59, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x25, 0x2e, 0x63,
	0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x61,
	0x74, 0x61, 0x44, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2e, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x61, 0x74, 0x61, 0x44, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x53, 0x0a,
	0x04, 0x52, 0x65, 0x61, 0x64, 0x12, 0x23, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74,
	0x2e, 0x52, 0x65, 0x61, 0x64, 0x44, 0x61, 0x74, 0x61, 0x44, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x63, 0x6f, 0x6e,
	0x74, 0x72, 0x61, 0x63, 0x74, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x44, 0x61, 0x74, 0x61, 0x44, 0x65,
	0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x59, 0x0a, 0x06, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x25, 0x2e, 0x63,
	0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x61,
	0x74, 0x61, 0x44, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2e, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x61, 0x74, 0x61, 0x44, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x59, 0x0a,
	0x06, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x25, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61,
	0x63, 0x74, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x44, 0x61, 0x74, 0x61, 0x44, 0x65, 0x66,
	0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26,
	0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x44, 0x61, 0x74, 0x61, 0x44, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x59, 0x0a, 0x06, 0x53, 0x65, 0x61, 0x72,
	0x63, 0x68, 0x12, 0x25, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2e, 0x53, 0x65,
	0x61, 0x72, 0x63, 0x68, 0x44, 0x61, 0x74, 0x61, 0x44, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x63, 0x6f, 0x6e, 0x74,
	0x72, 0x61, 0x63, 0x74, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x44, 0x61, 0x74, 0x61, 0x44,
	0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x42, 0x48, 0x5a, 0x46, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x74, 0x6d, 0x64, 0x73, 0x2d, 0x69, 0x6f, 0x2f, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72,
	0x64, 0x61, 0x74, 0x61, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2f, 0x64, 0x61,
	0x74, 0x61, 0x5f, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x3b, 0x64, 0x61,
	0x74, 0x61, 0x5f, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_contract_data_definition_data_definition_proto_rawDescOnce sync.Once
	file_contract_data_definition_data_definition_proto_rawDescData = file_contract_data_definition_data_definition_proto_rawDesc
)

func file_contract_data_definition_data_definition_proto_rawDescGZIP() []byte {
	file_contract_data_definition_data_definition_proto_rawDescOnce.Do(func() {
		file_contract_data_definition_data_definition_proto_rawDescData = protoimpl.X.CompressGZIP(file_contract_data_definition_data_definition_proto_rawDescData)
	})
	return file_contract_data_definition_data_definition_proto_rawDescData
}

var file_contract_data_definition_data_definition_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_contract_data_definition_data_definition_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_contract_data_definition_data_definition_proto_goTypes = []interface{}{
	(DataType)(0),                        // 0: contract.DataType
	(*DataDefinition)(nil),               // 1: contract.DataDefinition
	(*ReadDataDefinitionRequest)(nil),    // 2: contract.ReadDataDefinitionRequest
	(*ReadDataDefinitionResponse)(nil),   // 3: contract.ReadDataDefinitionResponse
	(*CreateDataDefinitionRequest)(nil),  // 4: contract.CreateDataDefinitionRequest
	(*CreateDataDefinitionResponse)(nil), // 5: contract.CreateDataDefinitionResponse
	(*UpdateDataDefinitionRequest)(nil),  // 6: contract.UpdateDataDefinitionRequest
	(*UpdateDataDefinitionResponse)(nil), // 7: contract.UpdateDataDefinitionResponse
	(*DeleteDataDefinitionRequest)(nil),  // 8: contract.DeleteDataDefinitionRequest
	(*DeleteDataDefinitionResponse)(nil), // 9: contract.DeleteDataDefinitionResponse
	(*SearchDataDefinitionRequest)(nil),  // 10: contract.SearchDataDefinitionRequest
	(*SearchDataDefinitionResponse)(nil), // 11: contract.SearchDataDefinitionResponse
	(*db.Timestamp)(nil),                 // 12: db.Timestamp
	(*arangodb.Filters)(nil),             // 13: arangodb.Filters
	(*arangodb.PaginationData)(nil),      // 14: arangodb.PaginationData
}
var file_contract_data_definition_data_definition_proto_depIdxs = []int32{
	0,  // 0: contract.DataDefinition.default_type:type_name -> contract.DataType
	12, // 1: contract.DataDefinition.updated_at:type_name -> db.Timestamp
	1,  // 2: contract.ReadDataDefinitionResponse.data_definition:type_name -> contract.DataDefinition
	1,  // 3: contract.CreateDataDefinitionRequest.data_definition:type_name -> contract.DataDefinition
	1,  // 4: contract.UpdateDataDefinitionRequest.data_definition:type_name -> contract.DataDefinition
	13, // 5: contract.SearchDataDefinitionRequest.filters:type_name -> arangodb.Filters
	1,  // 6: contract.SearchDataDefinitionResponse.data_definitions:type_name -> contract.DataDefinition
	14, // 7: contract.SearchDataDefinitionResponse.pagination:type_name -> arangodb.PaginationData
	4,  // 8: contract.DataDefinitionHandler.Create:input_type -> contract.CreateDataDefinitionRequest
	2,  // 9: contract.DataDefinitionHandler.Read:input_type -> contract.ReadDataDefinitionRequest
	6,  // 10: contract.DataDefinitionHandler.Update:input_type -> contract.UpdateDataDefinitionRequest
	8,  // 11: contract.DataDefinitionHandler.Delete:input_type -> contract.DeleteDataDefinitionRequest
	10, // 12: contract.DataDefinitionHandler.Search:input_type -> contract.SearchDataDefinitionRequest
	5,  // 13: contract.DataDefinitionHandler.Create:output_type -> contract.CreateDataDefinitionResponse
	3,  // 14: contract.DataDefinitionHandler.Read:output_type -> contract.ReadDataDefinitionResponse
	7,  // 15: contract.DataDefinitionHandler.Update:output_type -> contract.UpdateDataDefinitionResponse
	9,  // 16: contract.DataDefinitionHandler.Delete:output_type -> contract.DeleteDataDefinitionResponse
	11, // 17: contract.DataDefinitionHandler.Search:output_type -> contract.SearchDataDefinitionResponse
	13, // [13:18] is the sub-list for method output_type
	8,  // [8:13] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_contract_data_definition_data_definition_proto_init() }
func file_contract_data_definition_data_definition_proto_init() {
	if File_contract_data_definition_data_definition_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_contract_data_definition_data_definition_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataDefinition); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_contract_data_definition_data_definition_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadDataDefinitionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_contract_data_definition_data_definition_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadDataDefinitionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_contract_data_definition_data_definition_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateDataDefinitionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_contract_data_definition_data_definition_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateDataDefinitionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_contract_data_definition_data_definition_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateDataDefinitionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_contract_data_definition_data_definition_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateDataDefinitionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_contract_data_definition_data_definition_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteDataDefinitionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_contract_data_definition_data_definition_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteDataDefinitionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_contract_data_definition_data_definition_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchDataDefinitionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_contract_data_definition_data_definition_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchDataDefinitionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_contract_data_definition_data_definition_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_contract_data_definition_data_definition_proto_goTypes,
		DependencyIndexes: file_contract_data_definition_data_definition_proto_depIdxs,
		EnumInfos:         file_contract_data_definition_data_definition_proto_enumTypes,
		MessageInfos:      file_contract_data_definition_data_definition_proto_msgTypes,
	}.Build()
	File_contract_data_definition_data_definition_proto = out.File
	file_contract_data_definition_data_definition_proto_rawDesc = nil
	file_contract_data_definition_data_definition_proto_goTypes = nil
	file_contract_data_definition_data_definition_proto_depIdxs = nil
}
