// Code generated by protoc-gen-kore. DO NOT EDIT.

package segment

import (
	context "context"
	_ "embed"
	constant "gitlab.com/tmds-io/core-model/hyperion/contract.git/v2/contract/constant"
	masker "gitlab.com/tmds-io/core-model/hyperion/kore.git/v2/core/masker"
	sanitizer "gitlab.com/tmds-io/core-model/hyperion/kore.git/v2/core/sanitizer"
	validator "gitlab.com/tmds-io/core-model/hyperion/kore.git/v2/core/validator"
	client "gitlab.com/tmds-io/core-model/hyperion/kore.git/v2/service/client"
	errors "gitlab.com/tmds-io/core-model/hyperion/kore.git/v2/service/errors"
	server "gitlab.com/tmds-io/core-model/hyperion/kore.git/v2/service/server"
)

// Client API for SegmentHandler service

const SegmentHandlerRegistryServiceName = constant.RegistryServiceName + ".segment_handler"

type SegmentHandlerService interface {
	CreateSegment(ctx context.Context, in *CreateSegmentRequest, opts ...client.CallOption) (*CreateSegmentResponse, error)
	ReadSegment(ctx context.Context, in *ReadSegmentRequest, opts ...client.CallOption) (*ReadSegmentResponse, error)
	UpdateSegment(ctx context.Context, in *UpdateSegmentRequest, opts ...client.CallOption) (*UpdateSegmentResponse, error)
	DeleteSegment(ctx context.Context, in *DeleteSegmentRequest, opts ...client.CallOption) (*DeleteSegmentResponse, error)
	ListSegments(ctx context.Context, in *SearchSegmentsRequest, opts ...client.CallOption) (*SearchSegmentsResponse, error)
	AddSegmentValue(ctx context.Context, in *AddSegmentValueRequest, opts ...client.CallOption) (*AddSegmentValueResponse, error)
	AddChildSegmentValue(ctx context.Context, in *AddChildSegmentValueRequest, opts ...client.CallOption) (*AddChildSegmentValueResponse, error)
}

type segmentHandlerService struct {
	c    client.Client
	name string
}

func NewSegmentHandlerService(name string, c client.Client) SegmentHandlerService {
	return &segmentHandlerService{
		c:    c,
		name: name,
	}
}

func NewSegmentHandlerServiceDefault(clt ...client.Client) SegmentHandlerService {
	if 0 == len(clt) {
		clt = []client.Client{client.DefaultClient}
	}
	return NewSegmentHandlerService(constant.RegistryServiceName, clt[0])
}

func NewSegmentHandlerServiceWithDefaultClient() SegmentHandlerService {
	return NewSegmentHandlerService(constant.RegistryServiceName, client.DefaultClient)
}

func (c *segmentHandlerService) CreateSegment(ctx context.Context, in *CreateSegmentRequest, opts ...client.CallOption) (*CreateSegmentResponse, error) {
	req := c.c.NewRequest(c.name, "SegmentHandler.CreateSegment", in)
	out := new(CreateSegmentResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *segmentHandlerService) ReadSegment(ctx context.Context, in *ReadSegmentRequest, opts ...client.CallOption) (*ReadSegmentResponse, error) {
	req := c.c.NewRequest(c.name, "SegmentHandler.ReadSegment", in)
	out := new(ReadSegmentResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *segmentHandlerService) UpdateSegment(ctx context.Context, in *UpdateSegmentRequest, opts ...client.CallOption) (*UpdateSegmentResponse, error) {
	req := c.c.NewRequest(c.name, "SegmentHandler.UpdateSegment", in)
	out := new(UpdateSegmentResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *segmentHandlerService) DeleteSegment(ctx context.Context, in *DeleteSegmentRequest, opts ...client.CallOption) (*DeleteSegmentResponse, error) {
	req := c.c.NewRequest(c.name, "SegmentHandler.DeleteSegment", in)
	out := new(DeleteSegmentResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *segmentHandlerService) ListSegments(ctx context.Context, in *SearchSegmentsRequest, opts ...client.CallOption) (*SearchSegmentsResponse, error) {
	req := c.c.NewRequest(c.name, "SegmentHandler.ListSegments", in)
	out := new(SearchSegmentsResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *segmentHandlerService) AddSegmentValue(ctx context.Context, in *AddSegmentValueRequest, opts ...client.CallOption) (*AddSegmentValueResponse, error) {
	req := c.c.NewRequest(c.name, "SegmentHandler.AddSegmentValue", in)
	out := new(AddSegmentValueResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *segmentHandlerService) AddChildSegmentValue(ctx context.Context, in *AddChildSegmentValueRequest, opts ...client.CallOption) (*AddChildSegmentValueResponse, error) {
	req := c.c.NewRequest(c.name, "SegmentHandler.AddChildSegmentValue", in)
	out := new(AddChildSegmentValueResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for SegmentHandler service

// SegmentHandlerHandler is the server API for SegmentHandler service.
type SegmentHandlerHandler interface {
	CreateSegment(context.Context, *CreateSegmentRequest, *CreateSegmentResponse) error
	ReadSegment(context.Context, *ReadSegmentRequest, *ReadSegmentResponse) error
	UpdateSegment(context.Context, *UpdateSegmentRequest, *UpdateSegmentResponse) error
	DeleteSegment(context.Context, *DeleteSegmentRequest, *DeleteSegmentResponse) error
	ListSegments(context.Context, *SearchSegmentsRequest, *SearchSegmentsResponse) error
	AddSegmentValue(context.Context, *AddSegmentValueRequest, *AddSegmentValueResponse) error
	AddChildSegmentValue(context.Context, *AddChildSegmentValueRequest, *AddChildSegmentValueResponse) error
}

func RegisterSegmentHandlerHandler(s server.Server, hdlr SegmentHandlerHandler, opts ...server.HandlerOption) error {
	type segmentHandler interface {
		CreateSegment(ctx context.Context, in *CreateSegmentRequest, out *CreateSegmentResponse) error
		ReadSegment(ctx context.Context, in *ReadSegmentRequest, out *ReadSegmentResponse) error
		UpdateSegment(ctx context.Context, in *UpdateSegmentRequest, out *UpdateSegmentResponse) error
		DeleteSegment(ctx context.Context, in *DeleteSegmentRequest, out *DeleteSegmentResponse) error
		ListSegments(ctx context.Context, in *SearchSegmentsRequest, out *SearchSegmentsResponse) error
		AddSegmentValue(ctx context.Context, in *AddSegmentValueRequest, out *AddSegmentValueResponse) error
		AddChildSegmentValue(ctx context.Context, in *AddChildSegmentValueRequest, out *AddChildSegmentValueResponse) error
	}
	type SegmentHandler struct {
		segmentHandler
	}
	h := &segmentHandlerHandler{hdlr}
	return s.Handle(s.NewHandler(&SegmentHandler{h}, opts...))
}

type segmentHandlerHandler struct {
	SegmentHandlerHandler
}

//go:embed validation/segment_handler.create_segment.yaml
var ValidationTplOfCreateSegmentRequest string

//go:embed mask/segment_handler.create_segment.yaml
var MaskOfCreateSegmentRequest string

func (in *CreateSegmentRequest) Validate(ctx context.Context) error {
	if err := masker.ApplyFromYaml(in, MaskOfCreateSegmentRequest, true); err != nil {
		return err
	}
	return errors.WrapValidation(validator.ValidateSchema(ctx, in, ValidationTplOfCreateSegmentRequest))
}

//go:embed validation/segment_handler.read_segment.yaml
var ValidationTplOfReadSegmentRequest string

//go:embed mask/segment_handler.read_segment.yaml
var MaskOfReadSegmentRequest string

func (in *ReadSegmentRequest) Validate(ctx context.Context) error {
	if err := masker.ApplyFromYaml(in, MaskOfReadSegmentRequest, true); err != nil {
		return err
	}
	return errors.WrapValidation(validator.ValidateSchema(ctx, in, ValidationTplOfReadSegmentRequest))
}

//go:embed validation/segment_handler.update_segment.yaml
var ValidationTplOfUpdateSegmentRequest string

//go:embed mask/segment_handler.update_segment.yaml
var MaskOfUpdateSegmentRequest string

func (in *UpdateSegmentRequest) Validate(ctx context.Context) error {
	if err := masker.ApplyFromYaml(in, MaskOfUpdateSegmentRequest, true); err != nil {
		return err
	}
	return errors.WrapValidation(validator.ValidateSchema(ctx, in, ValidationTplOfUpdateSegmentRequest))
}

//go:embed validation/segment_handler.delete_segment.yaml
var ValidationTplOfDeleteSegmentRequest string

//go:embed mask/segment_handler.delete_segment.yaml
var MaskOfDeleteSegmentRequest string

func (in *DeleteSegmentRequest) Validate(ctx context.Context) error {
	if err := masker.ApplyFromYaml(in, MaskOfDeleteSegmentRequest, true); err != nil {
		return err
	}
	return errors.WrapValidation(validator.ValidateSchema(ctx, in, ValidationTplOfDeleteSegmentRequest))
}

//go:embed validation/segment_handler.list_segments.yaml
var ValidationTplOfSearchSegmentsRequest string

//go:embed mask/segment_handler.list_segments.yaml
var MaskOfSearchSegmentsRequest string

func (in *SearchSegmentsRequest) Validate(ctx context.Context) error {
	if err := masker.ApplyFromYaml(in, MaskOfSearchSegmentsRequest, true); err != nil {
		return err
	}
	return errors.WrapValidation(validator.ValidateSchema(ctx, in, ValidationTplOfSearchSegmentsRequest))
}

//go:embed validation/segment_handler.add_segment_value.yaml
var ValidationTplOfAddSegmentValueRequest string

//go:embed mask/segment_handler.add_segment_value.yaml
var MaskOfAddSegmentValueRequest string

func (in *AddSegmentValueRequest) Validate(ctx context.Context) error {
	if err := masker.ApplyFromYaml(in, MaskOfAddSegmentValueRequest, true); err != nil {
		return err
	}
	return errors.WrapValidation(validator.ValidateSchema(ctx, in, ValidationTplOfAddSegmentValueRequest))
}

//go:embed validation/segment_handler.add_child_segment_value.yaml
var ValidationTplOfAddChildSegmentValueRequest string

//go:embed mask/segment_handler.add_child_segment_value.yaml
var MaskOfAddChildSegmentValueRequest string

func (in *AddChildSegmentValueRequest) Validate(ctx context.Context) error {
	if err := masker.ApplyFromYaml(in, MaskOfAddChildSegmentValueRequest, true); err != nil {
		return err
	}
	return errors.WrapValidation(validator.ValidateSchema(ctx, in, ValidationTplOfAddChildSegmentValueRequest))
}

func (h *segmentHandlerHandler) CreateSegment(ctx context.Context, in *CreateSegmentRequest, out *CreateSegmentResponse) error {
	sanitizer.Sanitize(in)
	if err := in.Validate(ctx); err != nil {
		return err
	}
	return h.SegmentHandlerHandler.CreateSegment(ctx, in, out)
}

func (h *segmentHandlerHandler) ReadSegment(ctx context.Context, in *ReadSegmentRequest, out *ReadSegmentResponse) error {
	sanitizer.Sanitize(in)
	if err := in.Validate(ctx); err != nil {
		return err
	}
	return h.SegmentHandlerHandler.ReadSegment(ctx, in, out)
}

func (h *segmentHandlerHandler) UpdateSegment(ctx context.Context, in *UpdateSegmentRequest, out *UpdateSegmentResponse) error {
	sanitizer.Sanitize(in)
	if err := in.Validate(ctx); err != nil {
		return err
	}
	return h.SegmentHandlerHandler.UpdateSegment(ctx, in, out)
}

func (h *segmentHandlerHandler) DeleteSegment(ctx context.Context, in *DeleteSegmentRequest, out *DeleteSegmentResponse) error {
	sanitizer.Sanitize(in)
	if err := in.Validate(ctx); err != nil {
		return err
	}
	return h.SegmentHandlerHandler.DeleteSegment(ctx, in, out)
}

func (h *segmentHandlerHandler) ListSegments(ctx context.Context, in *SearchSegmentsRequest, out *SearchSegmentsResponse) error {
	sanitizer.Sanitize(in)
	if err := in.Validate(ctx); err != nil {
		return err
	}
	return h.SegmentHandlerHandler.ListSegments(ctx, in, out)
}

func (h *segmentHandlerHandler) AddSegmentValue(ctx context.Context, in *AddSegmentValueRequest, out *AddSegmentValueResponse) error {
	sanitizer.Sanitize(in)
	if err := in.Validate(ctx); err != nil {
		return err
	}
	return h.SegmentHandlerHandler.AddSegmentValue(ctx, in, out)
}

func (h *segmentHandlerHandler) AddChildSegmentValue(ctx context.Context, in *AddChildSegmentValueRequest, out *AddChildSegmentValueResponse) error {
	sanitizer.Sanitize(in)
	if err := in.Validate(ctx); err != nil {
		return err
	}
	return h.SegmentHandlerHandler.AddChildSegmentValue(ctx, in, out)
}
