// Code generated by protoc-gen-kresolver. DO NOT EDIT.

package category

import (
	fmt "fmt"
	server "gitlab.com/tmds-io/core-model/hyperion/kore.git/v2/service/server"
	strings "strings"
)

func RegisterHandlers(srv server.Server, services ...interface{}) error {
	registered := map[string]bool{
		"CategoryHandler": false,
	}
	for _, s := range services {
		name, err := RegisterHandler(srv, s)
		if err != nil {
			return err
		}
		if len(name) > 0 {
			registered[name] = true
		}
	}
	missing := make([]string, 0)
	for name, ok := range registered {
		if !ok {
			missing = append(missing, name)
		}
	}
	if len(missing) > 0 {
		return fmt.Errorf("all handlers must be registered while calling `%s.RegisterHandlers` but only %d/%d handler(s) were registered, missing: [`%s`].", "category", 1-len(missing), 1, strings.Join(missing, `, `))
	}
	return nil
}

func RegisterHandler(srv server.Server, service interface{}) (string, error) {
	if s, ok := service.(CategoryHandlerHandler); ok {
		return "CategoryHandler", RegisterCategoryHandlerHandler(srv, s)
	}
	return "", nil
}
