// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.21.12
// source: contract/data_value/data_value.proto

package data_value

import (
	data_definition "github.com/tmds-io/masterdata/contract/data_definition"
	db "gitlab.com/tmds-io/core-model/hyperion/kore.git/v2/core/db"
	arangodb "gitlab.com/tmds-io/core-model/hyperion/kore.git/v2/core/db/arangodb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DataValueStatus int32

const (
	DataValueStatus_CREATED    DataValueStatus = 0
	DataValueStatus_CONFIGURED DataValueStatus = 1
)

// Enum value maps for DataValueStatus.
var (
	DataValueStatus_name = map[int32]string{
		0: "CREATED",
		1: "CONFIGURED",
	}
	DataValueStatus_value = map[string]int32{
		"CREATED":    0,
		"CONFIGURED": 1,
	}
)

func (x DataValueStatus) Enum() *DataValueStatus {
	p := new(DataValueStatus)
	*p = x
	return p
}

func (x DataValueStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DataValueStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_contract_data_value_data_value_proto_enumTypes[0].Descriptor()
}

func (DataValueStatus) Type() protoreflect.EnumType {
	return &file_contract_data_value_data_value_proto_enumTypes[0]
}

func (x DataValueStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DataValueStatus.Descriptor instead.
func (DataValueStatus) EnumDescriptor() ([]byte, []int) {
	return file_contract_data_value_data_value_proto_rawDescGZIP(), []int{0}
}

type DataValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                string                   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                                          // Unique identifier for the DataValue
	Key               string                   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`                                                        // Unique Key code
	Expression        string                   `protobuf:"bytes,3,opt,name=expression,proto3" json:"expression,omitempty"`                                          // Expression of the data value
	MeasurementUnitId string                   `protobuf:"bytes,5,opt,name=measurement_unit_id,json=measurementUnitId,proto3" json:"measurement_unit_id,omitempty"` // UnitId of the data-value
	Type              data_definition.DataType `protobuf:"varint,6,opt,name=type,proto3,enum=contract.DataType" json:"type,omitempty"`                              // Type of the data-value
	From              *db.Timestamp            `protobuf:"bytes,7,opt,name=from,proto3" json:"from,omitempty"`                                                      // Date from which the data value is valid
	Till              *db.Timestamp            `protobuf:"bytes,8,opt,name=till,proto3" json:"till,omitempty"`                                                      // Date till which the data value is valid
	UpdatedAt         *db.Timestamp            `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`                           // Date of the last update
	GovernanceId      string                   `protobuf:"bytes,10,opt,name=governance_id,json=governanceId,proto3" json:"governance_id,omitempty"`                 // GovernanceId of the data-value
	SegmentIds        []string                 `protobuf:"bytes,11,rep,name=segment_ids,json=segmentIds,proto3" json:"segment_ids,omitempty"`                       // All Segments mapped with their value ids of the data-value
	Status            DataValueStatus          `protobuf:"varint,12,opt,name=status,proto3,enum=contract.DataValueStatus" json:"status,omitempty"`                  // Status of the DataValue (either CREATED or CONFIGURED)
}

func (x *DataValue) Reset() {
	*x = DataValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contract_data_value_data_value_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataValue) ProtoMessage() {}

func (x *DataValue) ProtoReflect() protoreflect.Message {
	mi := &file_contract_data_value_data_value_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataValue.ProtoReflect.Descriptor instead.
func (*DataValue) Descriptor() ([]byte, []int) {
	return file_contract_data_value_data_value_proto_rawDescGZIP(), []int{0}
}

func (x *DataValue) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DataValue) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *DataValue) GetExpression() string {
	if x != nil {
		return x.Expression
	}
	return ""
}

func (x *DataValue) GetMeasurementUnitId() string {
	if x != nil {
		return x.MeasurementUnitId
	}
	return ""
}

func (x *DataValue) GetType() data_definition.DataType {
	if x != nil {
		return x.Type
	}
	return data_definition.DataType(0)
}

func (x *DataValue) GetFrom() *db.Timestamp {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *DataValue) GetTill() *db.Timestamp {
	if x != nil {
		return x.Till
	}
	return nil
}

func (x *DataValue) GetUpdatedAt() *db.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *DataValue) GetGovernanceId() string {
	if x != nil {
		return x.GovernanceId
	}
	return ""
}

func (x *DataValue) GetSegmentIds() []string {
	if x != nil {
		return x.SegmentIds
	}
	return nil
}

func (x *DataValue) GetStatus() DataValueStatus {
	if x != nil {
		return x.Status
	}
	return DataValueStatus_CREATED
}

type GenerateDataValueVariationsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DataDefinitionId string   `protobuf:"bytes,1,opt,name=data_definition_id,json=dataDefinitionId,proto3" json:"data_definition_id,omitempty"`
	SegmentIds       []string `protobuf:"bytes,2,rep,name=segment_ids,json=segmentIds,proto3" json:"segment_ids,omitempty"`
}

func (x *GenerateDataValueVariationsRequest) Reset() {
	*x = GenerateDataValueVariationsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contract_data_value_data_value_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateDataValueVariationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateDataValueVariationsRequest) ProtoMessage() {}

func (x *GenerateDataValueVariationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contract_data_value_data_value_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateDataValueVariationsRequest.ProtoReflect.Descriptor instead.
func (*GenerateDataValueVariationsRequest) Descriptor() ([]byte, []int) {
	return file_contract_data_value_data_value_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateDataValueVariationsRequest) GetDataDefinitionId() string {
	if x != nil {
		return x.DataDefinitionId
	}
	return ""
}

func (x *GenerateDataValueVariationsRequest) GetSegmentIds() []string {
	if x != nil {
		return x.SegmentIds
	}
	return nil
}

type GenerateDataValueVariationsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DataValues []*DataValue `protobuf:"bytes,1,rep,name=data_values,json=dataValues,proto3" json:"data_values,omitempty"`
}

func (x *GenerateDataValueVariationsResponse) Reset() {
	*x = GenerateDataValueVariationsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contract_data_value_data_value_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateDataValueVariationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateDataValueVariationsResponse) ProtoMessage() {}

func (x *GenerateDataValueVariationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contract_data_value_data_value_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateDataValueVariationsResponse.ProtoReflect.Descriptor instead.
func (*GenerateDataValueVariationsResponse) Descriptor() ([]byte, []int) {
	return file_contract_data_value_data_value_proto_rawDescGZIP(), []int{2}
}

func (x *GenerateDataValueVariationsResponse) GetDataValues() []*DataValue {
	if x != nil {
		return x.DataValues
	}
	return nil
}

type ReadDataValueRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ReadDataValueRequest) Reset() {
	*x = ReadDataValueRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contract_data_value_data_value_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadDataValueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadDataValueRequest) ProtoMessage() {}

func (x *ReadDataValueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contract_data_value_data_value_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadDataValueRequest.ProtoReflect.Descriptor instead.
func (*ReadDataValueRequest) Descriptor() ([]byte, []int) {
	return file_contract_data_value_data_value_proto_rawDescGZIP(), []int{3}
}

func (x *ReadDataValueRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ReadDataValueResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DataValue *DataValue `protobuf:"bytes,1,opt,name=data_value,json=dataValue,proto3" json:"data_value,omitempty"`
}

func (x *ReadDataValueResponse) Reset() {
	*x = ReadDataValueResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contract_data_value_data_value_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadDataValueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadDataValueResponse) ProtoMessage() {}

func (x *ReadDataValueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contract_data_value_data_value_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadDataValueResponse.ProtoReflect.Descriptor instead.
func (*ReadDataValueResponse) Descriptor() ([]byte, []int) {
	return file_contract_data_value_data_value_proto_rawDescGZIP(), []int{4}
}

func (x *ReadDataValueResponse) GetDataValue() *DataValue {
	if x != nil {
		return x.DataValue
	}
	return nil
}

type UpdateDataValueRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DataValue *DataValue `protobuf:"bytes,1,opt,name=data_value,json=dataValue,proto3" json:"data_value,omitempty"`
}

func (x *UpdateDataValueRequest) Reset() {
	*x = UpdateDataValueRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contract_data_value_data_value_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateDataValueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDataValueRequest) ProtoMessage() {}

func (x *UpdateDataValueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contract_data_value_data_value_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDataValueRequest.ProtoReflect.Descriptor instead.
func (*UpdateDataValueRequest) Descriptor() ([]byte, []int) {
	return file_contract_data_value_data_value_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateDataValueRequest) GetDataValue() *DataValue {
	if x != nil {
		return x.DataValue
	}
	return nil
}

type UpdateDataValueResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DataValue *DataValue `protobuf:"bytes,1,opt,name=data_value,json=dataValue,proto3" json:"data_value,omitempty"`
}

func (x *UpdateDataValueResponse) Reset() {
	*x = UpdateDataValueResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contract_data_value_data_value_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateDataValueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDataValueResponse) ProtoMessage() {}

func (x *UpdateDataValueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contract_data_value_data_value_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDataValueResponse.ProtoReflect.Descriptor instead.
func (*UpdateDataValueResponse) Descriptor() ([]byte, []int) {
	return file_contract_data_value_data_value_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateDataValueResponse) GetDataValue() *DataValue {
	if x != nil {
		return x.DataValue
	}
	return nil
}

type DeleteDataValueRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteDataValueRequest) Reset() {
	*x = DeleteDataValueRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contract_data_value_data_value_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteDataValueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDataValueRequest) ProtoMessage() {}

func (x *DeleteDataValueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contract_data_value_data_value_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDataValueRequest.ProtoReflect.Descriptor instead.
func (*DeleteDataValueRequest) Descriptor() ([]byte, []int) {
	return file_contract_data_value_data_value_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteDataValueRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteDataValueResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteDataValueResponse) Reset() {
	*x = DeleteDataValueResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contract_data_value_data_value_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteDataValueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDataValueResponse) ProtoMessage() {}

func (x *DeleteDataValueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contract_data_value_data_value_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDataValueResponse.ProtoReflect.Descriptor instead.
func (*DeleteDataValueResponse) Descriptor() ([]byte, []int) {
	return file_contract_data_value_data_value_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteDataValueResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ConfigureDataValueRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DataValue *DataValue `protobuf:"bytes,1,opt,name=data_value,json=dataValue,proto3" json:"data_value,omitempty"` // ID of the DataValue to configure
}

func (x *ConfigureDataValueRequest) Reset() {
	*x = ConfigureDataValueRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contract_data_value_data_value_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfigureDataValueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureDataValueRequest) ProtoMessage() {}

func (x *ConfigureDataValueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contract_data_value_data_value_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureDataValueRequest.ProtoReflect.Descriptor instead.
func (*ConfigureDataValueRequest) Descriptor() ([]byte, []int) {
	return file_contract_data_value_data_value_proto_rawDescGZIP(), []int{9}
}

func (x *ConfigureDataValueRequest) GetDataValue() *DataValue {
	if x != nil {
		return x.DataValue
	}
	return nil
}

type ConfigureDataValueResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // ID of the configured DataValue
}

func (x *ConfigureDataValueResponse) Reset() {
	*x = ConfigureDataValueResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contract_data_value_data_value_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfigureDataValueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureDataValueResponse) ProtoMessage() {}

func (x *ConfigureDataValueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contract_data_value_data_value_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureDataValueResponse.ProtoReflect.Descriptor instead.
func (*ConfigureDataValueResponse) Descriptor() ([]byte, []int) {
	return file_contract_data_value_data_value_proto_rawDescGZIP(), []int{10}
}

func (x *ConfigureDataValueResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type SearchDataValueRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Filters *arangodb.Filters `protobuf:"bytes,1,opt,name=filters,proto3" json:"filters,omitempty"`
}

func (x *SearchDataValueRequest) Reset() {
	*x = SearchDataValueRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contract_data_value_data_value_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchDataValueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchDataValueRequest) ProtoMessage() {}

func (x *SearchDataValueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contract_data_value_data_value_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchDataValueRequest.ProtoReflect.Descriptor instead.
func (*SearchDataValueRequest) Descriptor() ([]byte, []int) {
	return file_contract_data_value_data_value_proto_rawDescGZIP(), []int{11}
}

func (x *SearchDataValueRequest) GetFilters() *arangodb.Filters {
	if x != nil {
		return x.Filters
	}
	return nil
}

type SearchDataValueResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DataValues []*DataValue             `protobuf:"bytes,1,rep,name=data_values,json=dataValues,proto3" json:"data_values,omitempty"` // List of retrieved Segments
	Pagination *arangodb.PaginationData `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (x *SearchDataValueResponse) Reset() {
	*x = SearchDataValueResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contract_data_value_data_value_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchDataValueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchDataValueResponse) ProtoMessage() {}

func (x *SearchDataValueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contract_data_value_data_value_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchDataValueResponse.ProtoReflect.Descriptor instead.
func (*SearchDataValueResponse) Descriptor() ([]byte, []int) {
	return file_contract_data_value_data_value_proto_rawDescGZIP(), []int{12}
}

func (x *SearchDataValueResponse) GetDataValues() []*DataValue {
	if x != nil {
		return x.DataValues
	}
	return nil
}

func (x *SearchDataValueResponse) GetPagination() *arangodb.PaginationData {
	if x != nil {
		return x.Pagination
	}
	return nil
}

var File_contract_data_value_data_value_proto protoreflect.FileDescriptor

var file_contract_data_value_data_value_proto_rawDesc = []byte{
	0x0a, 0x24, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x5f,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74,
	0x1a, 0x17, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x64, 0x62, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1d, 0x63, 0x6f, 0x72, 0x65, 0x2f,
	0x64, 0x62, 0x2f, 0x61, 0x72, 0x61, 0x6e, 0x67, 0x6f, 0x64, 0x62, 0x2f, 0x66, 0x69, 0x6c, 0x74,
	0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61,
	0x63, 0x74, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x92, 0x03, 0x0a, 0x09, 0x44, 0x61, 0x74,
	0x61, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x1e, 0x0a, 0x0a, 0x65, 0x78, 0x70, 0x72,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x65, 0x78,
	0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x2e, 0x0a, 0x13, 0x6d, 0x65, 0x61, 0x73,
	0x75, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x75, 0x6e, 0x69, 0x74, 0x5f, 0x69, 0x64, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x6d, 0x65, 0x61, 0x73, 0x75, 0x72, 0x65, 0x6d, 0x65,
	0x6e, 0x74, 0x55, 0x6e, 0x69, 0x74, 0x49, 0x64, 0x12, 0x26, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63,
	0x74, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x12, 0x21, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d,
	0x2e, 0x64, 0x62, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x04, 0x66,
	0x72, 0x6f, 0x6d, 0x12, 0x21, 0x0a, 0x04, 0x74, 0x69, 0x6c, 0x6c, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0d, 0x2e, 0x64, 0x62, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x52, 0x04, 0x74, 0x69, 0x6c, 0x6c, 0x12, 0x2c, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x64, 0x5f, 0x61, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x64, 0x62, 0x2e,
	0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x64, 0x41, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x67, 0x6f, 0x76, 0x65, 0x72, 0x6e, 0x61, 0x6e,
	0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x67, 0x6f, 0x76,
	0x65, 0x72, 0x6e, 0x61, 0x6e, 0x63, 0x65, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x65, 0x67,
	0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x0b, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a,
	0x73, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x73, 0x12, 0x31, 0x0a, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x63, 0x6f, 0x6e,
	0x74, 0x72, 0x61, 0x63, 0x74, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x73, 0x0a,
	0x22, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x44, 0x61, 0x74, 0x61, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x56, 0x61, 0x72, 0x69, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x2c, 0x0a, 0x12, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x64, 0x65, 0x66, 0x69,
	0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x10, 0x64, 0x61, 0x74, 0x61, 0x44, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x49,
	0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x49,
	0x64, 0x73, 0x22, 0x5b, 0x0a, 0x23, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x44, 0x61,
	0x74, 0x61, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x56, 0x61, 0x72, 0x69, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x34, 0x0a, 0x0b, 0x64, 0x61, 0x74,
	0x61, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13,
	0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x52, 0x0a, 0x64, 0x61, 0x74, 0x61, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x22,
	0x26, 0x0a, 0x14, 0x52, 0x65, 0x61, 0x64, 0x44, 0x61, 0x74, 0x61, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x4b, 0x0a, 0x15, 0x52, 0x65, 0x61, 0x64, 0x44,
	0x61, 0x74, 0x61, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x32, 0x0a, 0x0a, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2e,
	0x44, 0x61, 0x74, 0x61, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x09, 0x64, 0x61, 0x74, 0x61, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x22, 0x4c, 0x0a, 0x16, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x61,
	0x74, 0x61, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x32,
	0x0a, 0x0a, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x13, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2e, 0x44, 0x61,
	0x74, 0x61, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x09, 0x64, 0x61, 0x74, 0x61, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x22, 0x4d, 0x0a, 0x17, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x61, 0x74, 0x61,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a,
	0x0a, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x13, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2e, 0x44, 0x61, 0x74,
	0x61, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x09, 0x64, 0x61, 0x74, 0x61, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x22, 0x28, 0x0a, 0x16, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x44, 0x61, 0x74, 0x61, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x29, 0x0a, 0x17, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x44, 0x61, 0x74, 0x61, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x4f, 0x0a, 0x19, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x75, 0x72, 0x65, 0x44, 0x61, 0x74, 0x61, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x32, 0x0a, 0x0a, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61,
	0x63, 0x74, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x09, 0x64, 0x61,
	0x74, 0x61, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x2c, 0x0a, 0x1a, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x75, 0x72, 0x65, 0x44, 0x61, 0x74, 0x61, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x45, 0x0a, 0x16, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x44,
	0x61, 0x74, 0x61, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x2b, 0x0a, 0x07, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x11, 0x2e, 0x61, 0x72, 0x61, 0x6e, 0x67, 0x6f, 0x64, 0x62, 0x2e, 0x46, 0x69, 0x6c, 0x74,
	0x65, 0x72, 0x73, 0x52, 0x07, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x22, 0x89, 0x01, 0x0a,
	0x17, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x44, 0x61, 0x74, 0x61, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x34, 0x0a, 0x0b, 0x64, 0x61, 0x74, 0x61,
	0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e,
	0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x52, 0x0a, 0x64, 0x61, 0x74, 0x61, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x12, 0x38,
	0x0a, 0x0a, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x18, 0x2e, 0x61, 0x72, 0x61, 0x6e, 0x67, 0x6f, 0x64, 0x62, 0x2e, 0x50, 0x61,
	0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x0a, 0x70, 0x61,
	0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2a, 0x2e, 0x0a, 0x0f, 0x44, 0x61, 0x74, 0x61,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0b, 0x0a, 0x07, 0x43,
	0x52, 0x45, 0x41, 0x54, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x43, 0x4f, 0x4e, 0x46,
	0x49, 0x47, 0x55, 0x52, 0x45, 0x44, 0x10, 0x01, 0x32, 0xcb, 0x04, 0x0a, 0x10, 0x44, 0x61, 0x74,
	0x61, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x12, 0x7c, 0x0a,
	0x1b, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x44, 0x61, 0x74, 0x61, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x56, 0x61, 0x72, 0x69, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x2c, 0x2e, 0x63,
	0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65,
	0x44, 0x61, 0x74, 0x61, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x56, 0x61, 0x72, 0x69, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2d, 0x2e, 0x63, 0x6f, 0x6e,
	0x74, 0x72, 0x61, 0x63, 0x74, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x44, 0x61,
	0x74, 0x61, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x56, 0x61, 0x72, 0x69, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x5f, 0x0a, 0x12, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x65, 0x44, 0x61, 0x74, 0x61, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x12, 0x23, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2e, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x75, 0x72, 0x65, 0x44, 0x61, 0x74, 0x61, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63,
	0x74, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x65, 0x44, 0x61, 0x74, 0x61, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x50, 0x0a, 0x0d,
	0x52, 0x65, 0x61, 0x64, 0x44, 0x61, 0x74, 0x61, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1e, 0x2e,
	0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x44, 0x61, 0x74,
	0x61, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e,
	0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x44, 0x61, 0x74,
	0x61, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x56,
	0x0a, 0x0f, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x44, 0x61, 0x74, 0x61, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x12, 0x20, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2e, 0x53, 0x65, 0x61,
	0x72, 0x63, 0x68, 0x44, 0x61, 0x74, 0x61, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2e, 0x53,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x44, 0x61, 0x74, 0x61, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x56, 0x0a, 0x0f, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x44, 0x61, 0x74, 0x61, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x20, 0x2e, 0x63, 0x6f, 0x6e, 0x74,
	0x72, 0x61, 0x63, 0x74, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x61, 0x74, 0x61, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x63, 0x6f,
	0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x61, 0x74,
	0x61, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x56,
	0x0a, 0x0f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x44, 0x61, 0x74, 0x61, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x12, 0x20, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2e, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x44, 0x61, 0x74, 0x61, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2e, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x44, 0x61, 0x74, 0x61, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x3e, 0x5a, 0x3c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x6d, 0x64, 0x73, 0x2d, 0x69, 0x6f, 0x2f, 0x6d, 0x61, 0x73,
	0x74, 0x65, 0x72, 0x64, 0x61, 0x74, 0x61, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74,
	0x2f, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3b, 0x64, 0x61, 0x74, 0x61,
	0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_contract_data_value_data_value_proto_rawDescOnce sync.Once
	file_contract_data_value_data_value_proto_rawDescData = file_contract_data_value_data_value_proto_rawDesc
)

func file_contract_data_value_data_value_proto_rawDescGZIP() []byte {
	file_contract_data_value_data_value_proto_rawDescOnce.Do(func() {
		file_contract_data_value_data_value_proto_rawDescData = protoimpl.X.CompressGZIP(file_contract_data_value_data_value_proto_rawDescData)
	})
	return file_contract_data_value_data_value_proto_rawDescData
}

var file_contract_data_value_data_value_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_contract_data_value_data_value_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_contract_data_value_data_value_proto_goTypes = []interface{}{
	(DataValueStatus)(0),                        // 0: contract.DataValueStatus
	(*DataValue)(nil),                           // 1: contract.DataValue
	(*GenerateDataValueVariationsRequest)(nil),  // 2: contract.GenerateDataValueVariationsRequest
	(*GenerateDataValueVariationsResponse)(nil), // 3: contract.GenerateDataValueVariationsResponse
	(*ReadDataValueRequest)(nil),                // 4: contract.ReadDataValueRequest
	(*ReadDataValueResponse)(nil),               // 5: contract.ReadDataValueResponse
	(*UpdateDataValueRequest)(nil),              // 6: contract.UpdateDataValueRequest
	(*UpdateDataValueResponse)(nil),             // 7: contract.UpdateDataValueResponse
	(*DeleteDataValueRequest)(nil),              // 8: contract.DeleteDataValueRequest
	(*DeleteDataValueResponse)(nil),             // 9: contract.DeleteDataValueResponse
	(*ConfigureDataValueRequest)(nil),           // 10: contract.ConfigureDataValueRequest
	(*ConfigureDataValueResponse)(nil),          // 11: contract.ConfigureDataValueResponse
	(*SearchDataValueRequest)(nil),              // 12: contract.SearchDataValueRequest
	(*SearchDataValueResponse)(nil),             // 13: contract.SearchDataValueResponse
	(data_definition.DataType)(0),               // 14: contract.DataType
	(*db.Timestamp)(nil),                        // 15: db.Timestamp
	(*arangodb.Filters)(nil),                    // 16: arangodb.Filters
	(*arangodb.PaginationData)(nil),             // 17: arangodb.PaginationData
}
var file_contract_data_value_data_value_proto_depIdxs = []int32{
	14, // 0: contract.DataValue.type:type_name -> contract.DataType
	15, // 1: contract.DataValue.from:type_name -> db.Timestamp
	15, // 2: contract.DataValue.till:type_name -> db.Timestamp
	15, // 3: contract.DataValue.updated_at:type_name -> db.Timestamp
	0,  // 4: contract.DataValue.status:type_name -> contract.DataValueStatus
	1,  // 5: contract.GenerateDataValueVariationsResponse.data_values:type_name -> contract.DataValue
	1,  // 6: contract.ReadDataValueResponse.data_value:type_name -> contract.DataValue
	1,  // 7: contract.UpdateDataValueRequest.data_value:type_name -> contract.DataValue
	1,  // 8: contract.UpdateDataValueResponse.data_value:type_name -> contract.DataValue
	1,  // 9: contract.ConfigureDataValueRequest.data_value:type_name -> contract.DataValue
	16, // 10: contract.SearchDataValueRequest.filters:type_name -> arangodb.Filters
	1,  // 11: contract.SearchDataValueResponse.data_values:type_name -> contract.DataValue
	17, // 12: contract.SearchDataValueResponse.pagination:type_name -> arangodb.PaginationData
	2,  // 13: contract.DataValueHandler.GenerateDataValueVariations:input_type -> contract.GenerateDataValueVariationsRequest
	10, // 14: contract.DataValueHandler.ConfigureDataValue:input_type -> contract.ConfigureDataValueRequest
	4,  // 15: contract.DataValueHandler.ReadDataValue:input_type -> contract.ReadDataValueRequest
	12, // 16: contract.DataValueHandler.SearchDataValue:input_type -> contract.SearchDataValueRequest
	6,  // 17: contract.DataValueHandler.UpdateDataValue:input_type -> contract.UpdateDataValueRequest
	8,  // 18: contract.DataValueHandler.DeleteDataValue:input_type -> contract.DeleteDataValueRequest
	3,  // 19: contract.DataValueHandler.GenerateDataValueVariations:output_type -> contract.GenerateDataValueVariationsResponse
	11, // 20: contract.DataValueHandler.ConfigureDataValue:output_type -> contract.ConfigureDataValueResponse
	5,  // 21: contract.DataValueHandler.ReadDataValue:output_type -> contract.ReadDataValueResponse
	13, // 22: contract.DataValueHandler.SearchDataValue:output_type -> contract.SearchDataValueResponse
	7,  // 23: contract.DataValueHandler.UpdateDataValue:output_type -> contract.UpdateDataValueResponse
	9,  // 24: contract.DataValueHandler.DeleteDataValue:output_type -> contract.DeleteDataValueResponse
	19, // [19:25] is the sub-list for method output_type
	13, // [13:19] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_contract_data_value_data_value_proto_init() }
func file_contract_data_value_data_value_proto_init() {
	if File_contract_data_value_data_value_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_contract_data_value_data_value_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_contract_data_value_data_value_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateDataValueVariationsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_contract_data_value_data_value_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateDataValueVariationsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_contract_data_value_data_value_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadDataValueRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_contract_data_value_data_value_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadDataValueResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_contract_data_value_data_value_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateDataValueRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_contract_data_value_data_value_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateDataValueResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_contract_data_value_data_value_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteDataValueRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_contract_data_value_data_value_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteDataValueResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_contract_data_value_data_value_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfigureDataValueRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_contract_data_value_data_value_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfigureDataValueResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_contract_data_value_data_value_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchDataValueRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_contract_data_value_data_value_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchDataValueResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_contract_data_value_data_value_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_contract_data_value_data_value_proto_goTypes,
		DependencyIndexes: file_contract_data_value_data_value_proto_depIdxs,
		EnumInfos:         file_contract_data_value_data_value_proto_enumTypes,
		MessageInfos:      file_contract_data_value_data_value_proto_msgTypes,
	}.Build()
	File_contract_data_value_data_value_proto = out.File
	file_contract_data_value_data_value_proto_rawDesc = nil
	file_contract_data_value_data_value_proto_goTypes = nil
	file_contract_data_value_data_value_proto_depIdxs = nil
}
