// Code generated by protoc-gen-kresolver. DO NOT EDIT.

package container

import (
	segment "github.com/tmds-io/masterdata/contract/segment"
	mock "github.com/tmds-io/masterdata/contract/segment/mock"
	container "gitlab.com/tmds-io/core-model/hyperion/kore.git/v2/core/container"
)

func init() {
	// Registering SegmentHandler service
	container.Register(segment.NewSegmentHandlerServiceWithDefaultClient).
		Alias(segment.SegmentHandlerRegistryServiceName).
		Mock(mock.NewMockSegmentHandlerService).
		Tag("service.client").
		Lazy(true)
}
